### ISSUE TITLE
[Feature]: Remove the timeline section on home page

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#583]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/4d119476-6eb7-4042-8dd6-1f98cc396d1e)

### Describe the solution you'd like

Simple task: remove the timeline section and the code associated with it.

**Comment by Harsh-Aakoliya** [comment]
can you assign this problem to me ??

**Comment by Harsh-Aakoliya** [comment]
currently, the timeline section is between Founder's Note  and Social Media Pulse section 
After removing the timeline section the output will look like the below
![image](https://github.com/user-attachments/assets/07431e6d-3744-407b-8de0-06d4093b6b03)

**Comment by pradeeptosarkar** [comment]
go ahead @Harsh-Aakoliya

**Comment by Harsh-Aakoliya** [comment]
Just checkout PR https://github.com/namespacecomm/namespace-community-website/pull/603
for above issue

**Comment by pradeeptosarkar** [comment]
closed as completed
