### ISSUE TITLE
[Feature]: Make the navbar into a collapsible navbar on desktop screens

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#585]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/0232fb56-4508-4584-bbcb-130a8f657250)

### Describe the solution you'd like

We wish to make the navbar into a collapsible one for desktop screens.

**Comment by Neel-07** [comment]
@pradeeptosarkar can this issue be assigned to me

**Comment by pradeeptosarkar** [comment]
sure go ahead @Neel-07

**Comment by Neel-07** [comment]
@pradeeptosarkar   i have added a toggle button(slider) on the navbar, clicking that will show the nav items, by default it will be hidden for desktop screens .
<img width="1076" alt="image" src="https://github.com/user-attachments/assets/36ccc790-09da-4c07-bc09-96f141696466">
is this  okay?

**Comment by parthib2004** [comment]
Please assign this to me!

**Comment by pradeeptosarkar** [comment]
@Neel-07 in place of the slider can we have something like a 9 dots type button, which when clicked would open up the navbar

**Comment by pradeeptosarkar** [comment]
> @Neel-07 in place of the slider can we have something like a 9 dots type button, which when clicked would open up the navbar

![image](https://github.com/user-attachments/assets/53de6431-13dc-4496-b002-3cbe01ebd085)

something like this

**Comment by Neel-07** [comment]
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/dcbe2f1a-35eb-4cae-a1e4-7491e19b27c1">

@pradeeptosarkar does this look good?

**Comment by pradeeptosarkar** [comment]
yup @Neel-07

**Comment by Neel-07** [comment]
![Screenshot 2024-10-01 210247](https://github.com/user-attachments/assets/547db6c9-bf6e-4c82-a754-4999209cdc63)
fixed issue #588

**Comment by pradeeptosarkar** [comment]
closing as resolved
