### ISSUE TITLE
[Feature]: The Cyber Security page on the resources section lacks content

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#586]
### Is your feature request related to a problem? Please describe.

https://www.namespacecomm.in/cybersecurity

The Cyber Security section lacks content. For context you can view the other pages such as Web Dev, Machine Learning etc to add more content and pages to the Cyber Security one.

**Comment by aryamagarwal** [comment]
Hey @pradeeptosarkar, I would like to work on this issue. Please assign this to me under hacktoberfest'24.

**Comment by parthib2004** [comment]
Assign this to me!

**Comment by pradeeptosarkar** [comment]
go ahead @parthib2004
