### ISSUE TITLE
[Feature]: Adding projects to the project page

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#587]
### Is your feature request related to a problem? Please describe.

https://www.namespacecomm.in/projects

The projects page currently has only dummy cards. We have compiled a list of projects to be listed.

The projects data is available at: https://docs.google.com/spreadsheets/d/1DLHDZo0e_SweCihd0j386E_GnTETfbJMj1bgCpIocgI/edit?usp=sharing

We need the assignee to list these projects on the projects page. If any tweaks are required to the dummy component, feel free to do that.

The data must be pulled from a JSON file. A constants file is already present in the project which can be utilized.

**Comment by Sahil-Sinha-11** [comment]
Hey @pradeeptosarkar I would like to work on this issue.

**Comment by pradeeptosarkar** [comment]
Go ahead @Sahil-Sinha-11

**Comment by Sahil-Sinha-11** [comment]
Hey @pradeeptosarkar The projects whose images are not in file what should I do for them?

**Comment by pradeeptosarkar** [comment]
@Sahil-Sinha-11 you can apply a placeholder image for those projects

**Comment by Sahil-Sinha-11** [comment]
hey @pradeeptosarkar , I made PR . The only Issue was except one project all the other links were not wroking for image so I added a default img for them.

**Comment by pradeeptosarkar** [comment]
Its fine. Thanks for contributing @Sahil-Sinha-11
