### ISSUE TITLE
[Feature]: Fixing the Navbar Responsiveness

### ISSUE THREAD

**Issue by SahilTyagii** [namespacecomm/namespace-community-website#588]
### Is your feature request related to a problem? Please describe.

When opened on mobile, the "Connect with us" button is not vertically aligned with the hamburger button.
Also it feels excessive and cluttered in the navbar.
![WhatsApp Image 2024-09-29 at 14 03 27_047f00ea](https://github.com/user-attachments/assets/775784bf-a674-4e24-99a7-b680a6a596f9)

**Comment by SahilTyagii** [comment]
@aryamagarwal you can work on this, Congratulations!

**Comment by Neel-07** [comment]
@SahilTyagii  I am already working the issue #585 on Navbar.jsx file so can i take up this.

**Comment by pradeeptosarkar** [comment]
closing this as resolved
