### ISSUE TITLE
[Feature]: Fix animation overflow hidden in achievement cards

### ISSUE THREAD

**Issue by SahilTyagii** [namespacecomm/namespace-community-website#589]
### Is your feature request related to a problem? Please describe.

In the "Achievements" page, the cards have hover effect in which the card rotates and the achievement are displayed, but during the rotation the corners which are overflowing are not visible.

![image](https://github.com/user-attachments/assets/8362541e-96c1-4e8d-9a63-0eea1e7d203a)

**Comment by pritam0721** [comment]
can  I work on this @SahilTyagii ?

**Comment by SahilTyagii** [comment]
Yes @pritam0721 I have assigned it to you!

**Comment by SahilTyagii** [comment]
Hello @pritam0721 
I saw your solution, great work!
But i noticed that the card is shrinking on hover during rotation (which is fine), but when you take your cursor away during rotation, the card gets back to its original size and its corners are hidden again, will shrinking the card permanently to the size it is while hovering fix the issue?
![image](https://github.com/user-attachments/assets/25cbfc7e-59ea-46eb-ad11-1f651f67b028)
Also you reduced the animation speed and added a red border, I am assuming that you did this just to demonstrate the changes you made more clearly and you will revert the animation speed and border to how it was previously, right?

**Comment by pritam0721** [comment]
I added the red border also the animation speed is slow because  I am testing, and debugging the issue, and the demonstration purpose.

In the CSS class, the `card-container` takes the full height of the parent element there was no separation between them.
It seems good and one thing (Ps: it's just a suggestion ) I want to add is the animation is too fast I think.

**Comment by pradeeptosarkar** [comment]
yeah @pritam0721  buddy go ahead

**Comment by pritam0721** [comment]
@pradeeptosarkar  can you check it ?

**Comment by pradeeptosarkar** [comment]
closing as resolved. thanks for contributing @pritam0721
