### ISSUE TITLE
[Bug]: Missing image on Kubernetes page

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#591]
### Describe the bug

![image](https://github.com/user-attachments/assets/4c1417a0-f472-4de4-9747-361a37621dc1)

https://www.namespacecomm.in/kubernetes

**Comment by KNagaHariKrishna** [comment]
could you please assign me the above bug

**Comment by pradeeptosarkar** [comment]
sure go ahead @KNagaHariKrishna

**Comment by coder483** [comment]
do you have any image or i'll just put an kubernetes image ?

**Comment by parthib2004** [comment]
Can you please assign these to me?

**Comment by pradeeptosarkar** [comment]
closed as resolved

@coder483 @parthib2004 you guys can check out other open issues
