### ISSUE TITLE
[Bug]: Double footer on Rust page

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#592]
### Describe the bug

![image](https://github.com/user-attachments/assets/eb67e1f0-4236-46ff-8195-66e24ce495fb)

The extra footer needs to be removed. Possibly it is being rendered on the Rust page itself.

**Comment by KNagaHariKrishna** [comment]
@pradeeptosarkar 
I will fix the above issue can you please assign me.

**Comment by pradeeptosarkar** [comment]
sure go ahead @KNagaHariKrishna

**Comment by pradeeptosarkar** [comment]
closed as resolved

**Comment by pradeeptosarkar** [comment]
thanks for contributing @KNagaHariKrishna
