### ISSUE TITLE
[Feature]: Add content on Ethereum Page

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#593]
### Is your feature request related to a problem? Please describe.

The Ethereum page currently does not have any content. 
https://www.namespacecomm.in/blockchain/ethereum

The assignee is requested to build this page. Reference can be taken from the solidity page:
https://www.namespacecomm.in/blockchain/Solidity

**Comment by sambhavnrana** [comment]
Hello...

I can build the Ethereum content page matching the style of the Solidity page and also I have a bunch of resources related to Ethereum to add in there

**Comment by pradeeptosarkar** [comment]
go ahead @sambhavnrana

**Comment by pradeeptosarkar** [comment]
thanks for contributing @sambhavnrana 

closing this issue as resolved
