### ISSUE TITLE
[Feature]: Add content on Hyperledger Page

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#594]
### Is your feature request related to a problem? Please describe.

The Hyperledger page currently does not have any content. 
https://www.namespacecomm.in/blockchain/hyperledger-fabric

The assignee is requested to build this page. Reference can be taken from the solidity page:
https://www.namespacecomm.in/blockchain/Solidity

**Comment by KNagaHariKrishna** [comment]
@pradeeptosarkar 
Could you please assign it to me, I am interested in working on it

**Comment by pradeeptosarkar** [comment]
yeah go ahead @KNagaHariKrishna

**Comment by pradeeptosarkar** [comment]
Closing as resolved. Thanks for contributing @KNagaHariKrishna
