### ISSUE TITLE
[Feature]: Add content on Truffle page

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#595]
### Is your feature request related to a problem? Please describe.

The Truffle page currently does not have any content. 
https://www.namespacecomm.in/blockchain/truffle

The assignee is requested to build this page. Reference can be taken from the solidity page:
https://www.namespacecomm.in/blockchain/Solidity

**Comment by AlaminPu1007** [comment]
hey @pradeeptosarkar I'd like to work on this issue.

**Comment by pradeeptosarkar** [comment]
go ahead @AlaminPu1007

**Comment by AlaminPu1007** [comment]
@pradeeptosarkar  To design the truffle page, I would need more details on the specific content that should be included. Could you provide a draft, an outline, or any resources that would help me add relevant information? Any reference materials would also be helpful to ensure the content aligns with the project's goals.

**Comment by pradeeptosarkar** [comment]
@AlaminPu1007 there are no fixed guidelines as such. All the pages under the resources section have been built to provide the necessary starting info to anyone willing to learn that specific tech. So feel free add in your creativity and intellect into it. And you can refer to various other similar pages in the resources section for ideas and reusable components.

**Comment by pradeeptosarkar** [comment]
closing as resolved
