### ISSUE TITLE
[Feature]: Add content to the cryptocurrency page

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#596]
### Is your feature request related to a problem? Please describe.

The Crypto Currency page currently does not have any content. 
https://www.namespacecomm.in/blockchain/cryptocurrency

The assignee is requested to build this page. Reference can be taken from the other pages in the resource section
https://www.namespacecomm.in/resources

**Comment by hgjajoo** [comment]
Hey! can I work on this? I have a brief idea about how cryptocurrency works, also I could pull some content from the web!

**Comment by pradeeptosarkar** [comment]
sure go ahead @hgjajoo

**Comment by hgjajoo** [comment]
@pradeeptosarkar  I've sent a pr!
