### ISSUE TITLE
[Feature]: Add content to the Supply Chain Management page

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#597]
### Is your feature request related to a problem? Please describe.

The Supply Chain Management page currently does not have any content. 
https://www.namespacecomm.in/blockchain/supply-chain-management

The assignee is requested to build this page. Reference can be taken from the other pages in the resource section
https://www.namespacecomm.in/resources

**Comment by KNagaHariKrishna** [comment]
@pradeeptosarkar  Could you please assign this feature to me I will work on it

**Comment by pradeeptosarkar** [comment]
yeah go ahead @KNagaHariKrishna

**Comment by pradeeptosarkar** [comment]
closing as resolved
