### ISSUE TITLE
[Feature]: The JavaScript page under UI/UX needs to be directed to proper file

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#599]
### Is your feature request related to a problem? Please describe.

The JavaScript page in the UI/UX section is missing
https://www.namespacecomm.in/javascript

![image](https://github.com/user-attachments/assets/a4203b85-8f0e-4aea-be0f-c40bced0deec)

There is a "js" page under the web development section. The assignee is requested to make the UI/UX section's JavaScript button to open this pre-existing page
https://www.namespacecomm.in/js

**Comment by TruLie13** [comment]
Just pushed an MR. Waiting for review.
