### ISSUE TITLE
[Bug]: Development Path components on the React Native page open to blank pages

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#600]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/41451430-d668-4855-9644-7e8172019c92)

These components do not need to open new pages, as those pages are missing. So remove redirects

**Comment by RudraJy** [comment]
Hey @pradeeptosarkar I'd like to work on this issue.

**Comment by pradeeptosarkar** [comment]
Sure @RudraJy go ahead

**Comment by pradeeptosarkar** [comment]
closing as resolved
