### ISSUE TITLE
[Bug]: Wierd blue line appears on page reload

### ISSUE THREAD

**Issue by PranavBarthwal** [namespacecomm/namespace-community-website#613]
### Describe the bug

Wierd blue line or scrollbar appears on page reload

![image](https://github.com/user-attachments/assets/e9bb8609-7f1c-4020-80ae-54ef427fb3dc)

**Comment by ptskok** [comment]
hi, can I work on this?

**Comment by ptskok** [comment]
@PranavBarthwal hello, can I work on this?

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal hello, can I work on this?

Yeah sure. Assigned.

**Comment by ptskok** [comment]
Hi, I created a [PR](https://github.com/namespacecomm/namespace-community-website/pull/619)

**Comment by pradeeptosarkar** [comment]
closing this as resolved. thanks for contributing @ptskok
