### ISSUE TITLE
[Feature]: Add new page for Algorena 

### ISSUE THREAD

**Issue by PranavBarthwal** [namespacecomm/namespace-community-website#614]
### Is your feature request related to a problem? Please describe.

Add new page for Algorena, similar to other event oages like techX and HACKHAZARDS
content for the page will be provided once the issue is assigned
![Screenshot (332)](https://github.com/user-attachments/assets/8413ee86-713c-4f2a-b75a-03d5a0ab291b)

![image](https://github.com/user-attachments/assets/bb625ce4-74e4-40bb-bf0f-e4c57249444a)

**Comment by ArshTiwari2004** [comment]
@PranavBarthwal assign this to me and provide the content.

**Comment by AlaminPu1007** [comment]
@PranavBarthwal can I work on this?

**Comment by AADESHak007** [comment]
Hey @PranavBarthwal I am very keen to work on this issue . I would be really happy if you could assign this issue to me.

**Comment by anuj846k** [comment]
Hi  @PranavBarthwal  can you provide some content for this page, please?

**Comment by pradeeptosarkar** [comment]
closing since no longer required
