### ISSUE TITLE
[Bug]: Contact us button at the Hackhazards sponsors page should redirect to Gmail

### ISSUE THREAD

**Issue by ArshTiwari2004** [namespacecomm/namespace-community-website#615]
### Expected Behavior

The contact us button should redirect to G-mail.

### Screenshot/ Video

![Screenshot 2024-10-01 220800](https://github.com/user-attachments/assets/e47fbad1-bf28-41b4-bcdc-0089e3dafdd0)

**Comment by pradeeptosarkar** [comment]
@ArshTiwari2004 the mail to be used is: contact@namespacecomm.in

**Comment by pradeeptosarkar** [comment]
closing as resolved
