### ISSUE TITLE
[Feature]:  Add ESLint, Prettier, and Husky

### ISSUE THREAD

**Issue by AlaminPu1007** [namespacecomm/namespace-community-website#625]
I would like to propose adding ESLint, Prettier, and Husky to the project to improve code quality and consistency, as well as automate the process of code linting and formatting.

- **ESLint :** - Helps identify and fix potential syntax errors, best practices, and code style violations.
 - **Prettier :** - Ensures consistent code formatting across the codebase, reducing manual formatting.
 - **Husky  :** - Automates running linting and formatting tasks before commits to prevent code quality issues from reaching the main branch.

### Describe the solution you'd like

1.  Install ESLint
2. Install Prettier
3. Setup Husky

**Comment by pradeeptosarkar** [comment]
@AlaminPu1007 we are not looking to add as of now. Thanks for opening the issue. Feel free to open any other issue
