### ISSUE TITLE
[Feature]: Enhancing the UI of the Social media and the FAQ's section

### ISSUE THREAD

**Issue by AADESHak007** [namespacecomm/namespace-community-website#630]
### Is your feature request related to a problem? Please describe.

The layout and  the background of the website is really good but the social media section is really very static and it can  be enhanced with animation and a better way of presenting it  .
The FAQ section is tooo bluish and it takes a huge amount of space so it can be enhanced too .
![Screenshot 2024-10-02 213100](https://github.com/user-attachments/assets/6e781513-5e33-4f0a-9ab0-d3f591e0c06c)
![Screenshot 2024-10-02 213043](https://github.com/user-attachments/assets/f79d5f2a-46d2-40b1-b80a-5253ebf73a15)

### Describe the solution you'd like

I would like to add a  bit of animation to it using GSAP  or I can change the layout of these sections to make them  more exhilarating to scroll.

### Additional context

Please assign this issue to me

**Comment by AADESHak007** [comment]
I would like you to assign this to me under hacktoberfest 2024

**Comment by PranavBarthwal** [comment]
Go ahead!

**Comment by pradeeptosarkar** [comment]
closing as resolved
