### ISSUE TITLE
[Feature]: Change the twitter icon to the updated icon of twitter

### ISSUE THREAD

**Issue by anamelahi** [namespacecomm/namespace-community-website#633]
### Is your feature request related to a problem? Please describe.

The footer contains the social icons, where the twitter icon is outdated. 
![Screenshot 2024-10-04 144001](https://github.com/user-attachments/assets/b9dcc6b2-b576-40a8-b326-074869b3e8d1)

### Describe the solution you'd like

I would like to update that to the new icon.

**Comment by anamelahi** [comment]
kindly assign it to me

**Comment by pradeeptosarkar** [comment]
@anamelahi go ahead
