### ISSUE TITLE
[Feature]: Create a new page for Chapters

### ISSUE THREAD

**Issue by pradeeptosarkar** [namespacecomm/namespace-community-website#634]
### Is your feature request related to a problem? Please describe.

- We need a new page for chapters
- to be accessible at /chapters
- add it in the home page navbar as well
- no content to be added as of now only a blank page
- only a one line title should be there at the top of the page as "nameSpace Chapters"
- ensure the page is consistent with other pages on the website in terms of UI (bg color, naming, file location, routing etc.)

**Comment by ShahAnuj2610** [comment]
hi @pradeeptosarkar, i can work on this

**Comment by SIDHARTH20K4** [comment]
Hello @pradeeptosarkar 
I would like to work on this issue!!

**Comment by pradeeptosarkar** [comment]
Assigned to you @ShahAnuj2610 

@SIDHARTH20K4 more issues on this page would soon be available..!

**Comment by SIDHARTH20K4** [comment]
@pradeeptosarkar 
sure!!

**Comment by pradeeptosarkar** [comment]
closing as resolved. thanks for contributing @ShahAnuj2610
