### ISSUE TITLE
[Bug]: The namespace projects page has overlapping text on top of images in the project card

### ISSUE THREAD

**Issue by sanjesh17** [namespacecomm/namespace-community-website#640]
### Describe the bug

The namespace projects page has overlapping text on top of images in the project card and looks like the position of everything is overriding and not optimized well

### To Reproduce

1. Go to Projects in the Navbar
2. See error

### Expected Behavior

The page looks ugly

**Comment by aLok-1105** [comment]
@sanjesh17 Can I work on this issue ?

**Comment by lohitkolluri** [comment]
Hey please assign this issue to me
