### ISSUE TITLE
[Feature]: Improve Footer Responsiveness and Add Target="_blank" for External Links

### ISSUE THREAD

**Issue by lohitkolluri** [namespacecomm/namespace-community-website#641]
### Is your feature request related to a problem? Please describe.

I'm frustrated when users click on external links in the footer, and they navigate away from the main website, disrupting the user experience. Additionally, the footer responsiveness could be improved for mobile devices, as spacing and alignment aren't optimal on smaller screens.

### Describe the solution you'd like

I want to enhance the responsiveness of the footer by improving its layout for mobile devices (better spacing, text alignment, and icon size). Additionally, all external links in the footer should open in a new tab using target="_blank" to prevent users from navigating away from the current page.

### Describe alternatives you've considered

I considered leaving the current footer as-is, but this would continue to cause issues with users being taken away from the main site when clicking on external links. Another option was to use a modal or in-page navigation for social links, but this would disrupt the standard behavior expected by users.

### Additional context

You can see the current layout of the footer in the screenshot below. The improved version should maintain a clean, simple look while ensuring that all icons and links are properly sized and spaced for different screen sizes. 
Old:
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/c2b21243-15b6-4b33-b663-643cdbc2523f">

New:
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/dabefa5b-6163-4cb1-af9a-ce360120e83c">

**Comment by lohitkolluri** [comment]
Please Assign the work to me.

Thank You

**Comment by lohitkolluri** [comment]
@pradeeptosarkar Done please check the PR and can you please assign me some other issue.

Thank You!!

**Comment by pradeeptosarkar** [comment]
closing as resolved
