### ISSUE TITLE
[Bug]: Images Not Loading on Achievements Page - Add Placeholder Support

### ISSUE THREAD

**Issue by lohitkolluri** [namespacecomm/namespace-community-website#643]
### Describe the bug

Some images on the Achievements Page are not loading correctly. This leaves blank spaces where the images should appear, making the page look incomplete and reducing the overall user experience.

### To Reproduce

Go to the Achievements Page of the application.
Scroll down to view the list of achievements with images.
Observe the missing or broken images.
See the error—either no image or an empty space is shown.

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/c8a741b7-d85e-4c37-8378-98d442cb337c">

### Expected Behavior

I expected all images to load properly. In the case of broken image links or slow loading times, a placeholder image or a loading icon should be displayed to avoid blank spaces.

### Screenshot/ Video

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/883d5625-7948-44d4-8cb0-ca657098ce72">

### Desktop (please complete the following information)

Device: Macbook Pro
OS: Mac Os Sequoia
Browser: Chrome

**Comment by pradeeptosarkar** [comment]
closing as resolved
