### ISSUE TITLE
[Bug]: Navbar Items Not aligned centered 

### ISSUE THREAD

**Issue by anuj846k** [namespacecomm/namespace-community-website#646]
### Describe the bug

In the mobile **Navbar**, the hamburger icon and the connect with us button are not aligned properly which Gives an inconsistent look.

### To Reproduce

1. Go to the namespace community website
2. Resize the browser window to a mobile view 
3. Scroll down to see Navbar 
4. Observe the alignment of the Navbar items
5. Notice that the hamburger icon and the button are not centred or aligned as expected.

### Expected Behavior

The mobile Navbar should have all items, including the hamburger icon and the "Connect with us" button, aligned centrally and evenly spaced

### Screenshot/ Video

![image](https://github.com/user-attachments/assets/c0cf3dfa-977e-4dc5-b447-d93ca5e5e212)

### Desktop (please complete the following information)

Device - Realme 8
OS - Android
Browser - Chrome
Version - 95.0.4638.69 (for Chrome)

**Comment by imkhateeb** [comment]
Hey @anuj846k I would like to work on this issue. Please assign it to me.
