### ISSUE TITLE
[Bug]: Frequently asked question section not visible on mobile

### ISSUE THREAD

**Issue by anuj846k** [namespacecomm/namespace-community-website#648]
### Describe the bug

The FAQ section is not visible on mobile 

### To Reproduce

1. Go to the namespace community website
2. Resize the browser window to a mobile view
3. Scroll down to FAQ section
4. Notice the FAQ section is hidden 

### Expected Behavior

The FAQ Section should be visible on the mobile screen as well 

### Screenshot/ Video

![Screenshot from 2024-10-08 15-03-45](https://github.com/user-attachments/assets/1b89afc8-cae8-43d5-9fc1-1f407b677b2a)

### Desktop (please complete the following information)

Device - Realme 8
OS - Android
Browser - Chrome
Version - 95.0.4638.69 (for Chrome)

### Additional context

In the **Mobile screen**
Also, the YouTube section should use flex col and more width to make the video visible properly.

![image](https://github.com/user-attachments/assets/ac7004fa-f105-4bee-8490-d286f2f7843e)

**Comment by lohitkolluri** [comment]
@pradeeptosarkar i think this issue is resolved due to the updated FAQ Section

**Comment by anuj846k** [comment]
oh okay, no problem! I am also working on the additional problem that I mentioned

**Comment by pradeeptosarkar** [comment]
closing as resolved. Thanks for contributing @anuj846k
