### ISSUE TITLE
[Bug]: Improper Alignment in FAQ Component

### ISSUE THREAD

**Issue by lohitkolluri** [namespacecomm/namespace-community-website#650]
### Describe the bug

The FAQ section is not aligned properly, causing visual inconsistencies and affecting the overall layout of the application.

### To Reproduce

1. Go to the FAQ section of the application.
2. Observe the alignment of the FAQ Dropdown with Frequenty Asked Questions title

### Expected Behavior

The FAQ items should be centered and aligned consistently, creating a visually appealing and structured layout.

### Screenshot/ Video

<img width="1105" alt="image" src="https://github.com/user-attachments/assets/1bb6a5a6-8391-4429-9a22-afd9b1f66170">

### Desktop (please complete the following information)

Device: MacBook Pro
OS: Mac OS Sequioa
Browser: Chrome

**Comment by pradeeptosarkar** [comment]
go ahead @lohitkolluri

**Comment by lohitkolluri** [comment]
@pradeeptosarkar Please check my PR i revamped the FAQ Section and along with that adjusted the size for send button in ContactUS Section

**Comment by pradeeptosarkar** [comment]
closing as resolved. thanks for contributing @lohitkolluri
