### ISSUE TITLE
[Feature]: animation on project to improve the interaction with use and mordern look

### ISSUE THREAD

**Issue by Adeesh-bode** [namespacecomm/namespace-community-website#662]
### Is your feature request related to a problem? Please describe.

Not a problem , yes a enhancement to ui

### Describe the solution you'd like

Animation based on components visisbility , scroll animations ,  pop up animation . Will share a demo video on pr, when assigned

**Comment by pradeeptosarkar** [comment]
go ahead @Adeesh-bode

**Comment by Adeesh-bode** [comment]
Thanks pradeep , I will soon start working on it!!!

**Comment by Adeesh-bode** [comment]
Hey Pradeep, apologies for not updating you earlier. I was working on another issue, but I've completed that now. I'm currently working on this and will update you on the progress shortly.

**Comment by pradeeptosarkar** [comment]
closing since no longer required
