### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mayank-704** [namespacecomm/namespace-community-website#666]
### Describe the bug

There is a content alignment issue in the Project cards section. The fixed height of the Project card causes the icons to overflow in the "Bubble Game" project due to excess text content.

### To Reproduce

Steps to reproduce the issue
1. Go to 'Projects '.
2. Scroll Down to 'Bubble Game' card.
3. See bug. 

### Expected Behavior

Expected Behavior - Icons Should not be overflow from card. And height of card should be adjusted to filled content.

### Screenshot/ Video

![](https://drive.google.com/uc?export=view&id=1rqSZWrG-Pp3deBJ9C1wBpsX_OXvsHpd0)

### Desktop (please complete the following information)

Device - Lenovo ThinkPad X380 Yoga
OS - Windows 11
Browser - Chrome
Version - 129.0.6668.90

### Additional context

I can effectively address this issue with ease.

**Comment by Mayank-704** [comment]
Hey @pradeeptosarkar! I’d be happy to take on this task. I can handle it and ensure that no new bugs pop up. Let me know!

**Comment by pradeeptosarkar** [comment]
Hi @Mayank-704 this page will be taken down so we are not looking to update it
