### ISSUE TITLE
[Feature]: FAQ Rerender

### ISSUE THREAD

**Issue by rhnas110** [namespacecomm/namespace-community-website#667]
### Is your feature request related to a problem? Please describe.

When i open the FAQ item, it always re render. When I opened the code, there was a useState to handle the FAQ item. It should be possible to solve it without useState, and will further improve performance.
![image](https://github.com/user-attachments/assets/2c6a661b-89ed-4711-ac49-4adf75a4237b)
https://github.com/user-attachments/assets/e8153e6d-f341-4475-9ff2-c04e160be566

### Describe the solution you'd like

1. I will work on src/Sections/Faq/Faq.jsx
2. I will delete the useState change to primitive way like i use custom property name data-state and combine with CSS

### Additional context

Sir @namespace-admin @pradeeptosarkar  can you assign this issue to me Sir? I am new to open source contributions and I would love to contribute to your project Sir. I also participated in Hacktoberfest2024.

**Comment by pradeeptosarkar** [comment]
closing this as no longer required
