### ISSUE TITLE
[Feature]: Update Accordion Design in FAQ Section

### ISSUE THREAD

**Issue by TJ-2004** [namespacecomm/namespace-community-website#668]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when users interact with the current accordion, which seems outdated in its design. The current accordion style is visually heavy, and its UX can be improved to provide a more streamlined and user-friendly interface, especially when compared to other modern web design standards.

### Describe the solution you'd like

I would like to replace the current accordion design with a more modern, streamlined version (similar to the second image attached). The new design is simpler, cleaner, and easier for users to navigate.

Improved accessibility for all users.
A more modern look and feel.
Easier interaction for mobile users.

### Describe alternatives you've considered

An alternative could be to offer multiple accordion design options within the project, allowing users to choose between a traditional or modern design, depending on their preference. However, I believe a default switch to the more modern style will be the most user-friendly.

### Additional context

I’ve attached screenshots of the current accordion and the proposed design for comparison. The new accordion style is more minimal, with improved spacing, fonts, and an overall sleek feel, which aligns with modern UI/UX standards. This change would enhance both the aesthetics and usability of the project.
Current Design:<img width="978" alt="Screenshot 2024-10-22 at 8 45 38 PM" src="https://github.com/user-attachments/assets/0269c7e2-fd0e-4578-b5a4-5ed4949aa2b0">
Proposed Design: <img width="701" alt="Screenshot 2024-10-22 at 9 05 02 PM" src="https://github.com/user-attachments/assets/26d875ad-b521-4934-befd-a33bedac460d">

**Comment by TJ-2004** [comment]
Hi @pradeeptosarkar @anuj846k  , I’ve submitted the feature request for the accordion under the FAQ section. Could you kindly review it and let me know if it’s good to proceed? Once approved, I’d be happy to start working on it and submit a PR. Thanks!

**Comment by pradeeptosarkar** [comment]
closing this as no longer required
